export const COMPANY = {
  name: "Microcomp",
  fullName: "Microcomp Dariusz Kmieciński",
  address: "ul. Willowa 4, 72-410 Gardno",
  city: "Gardno",
  county: "powiat gryficki",
  voivodeship: "województwo zachodniopomorskie",
  phone: "+48 502 568 438",
  email: "microcomp@microcomp.co",
  website: "https://microcomp.co",
  nip: "855-000-00-00",
  regon: "000000000",
  googleRating: 4.9,
  googleReviews: 28,
  yearFounded: 2000,
  itActivitySince: 1997,
  yearsExperience: new Date().getFullYear() - 2000,
  serviceArea: [
    "Gardno",
    "Nowogard",
    "Gryfice",
    "Kamień Pomorski",
    "Szczecin",
    "Goleniów",
    "Gryfino",
    "Stargard",
    "Police",
    "Pyrzyce",
    "Gorzów Wielkopolski",
    "Zielona Góra",
    "Szczecinek",
    "Trzebiatów",
  ],
  partners: ["Comarch Optima", "PcBiznes", "Microsoft"],
  services: [
    "monitoring-cctv",
    "it-dla-firm",
    "strony-internetowe",
    "sieci-komputerowe",
    "oprogramowanie-biurowe",
    "backup-danych",
  ],
};

export const SCHEMA_LOCAL_BUSINESS: Record<string, unknown> = {
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  "@id": "https://microcomp.co/#organization",
  "name": "Microcomp Dariusz Kmieciński",
  "description":
    "Kompleksowa obsługa IT dla firm i instytucji. Monitoring CCTV, systemy alarmowe, sieci komputerowe, Comarch Optima, strony WWW, serwis PC.",
  "url": "https://microcomp.co",
  "telephone": COMPANY.phone,
  "email": COMPANY.email,
  "image": "https://microcomp.co/about-office.jpg",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "Willowa 4",
    "addressLocality": "Gardno",
    "addressRegion": "województwo zachodniopomorskie",
    "postalCode": "72-410",
    "addressCountry": "PL",
  },
  "geo": {
    "@type": "GeoCoordinates",
    "latitude": 53.85,
    "longitude": 14.85,
  },
  "areaServed": COMPANY.serviceArea.map((name) => ({
    "@type": "City",
    name,
  })),
  "foundingDate": "2000",
  "numberOfEmployees": "1–10",
  "openingHoursSpecification": {
    "@type": "OpeningHoursSpecification",
    "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    "opens": "09:00",
    "closes": "17:00",
  },
  "priceRange": "$$",
  "sameAs": [],
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": COMPANY.googleRating,
    "reviewCount": COMPANY.googleReviews,
    "bestRating": "5",
    "worstRating": "1",
  },
  "hasOfferCatalog": {
    "@type": "OfferCatalog",
    "name": "Usługi IT i zabezpieczeń",
    "itemListElement": COMPANY.services.map((slug) => ({
      "@type": "Offer",
      "itemOffered": {
        "@type": "Service",
        "name": slug,
        "url": `https://microcomp.co/uslugi/${slug}`,
      },
    })),
  },
};

export const BLOG_POSTS = [
  {
    slug: "monitoring-cctv-ceny-2024",
    title: "Ile kosztuje monitoring CCTV w 2024 roku?",
    excerpt:
      "Ceny systemów monitoringu CCTV znacząco spadły w ostatnich latach. Sprawdź, ile kosztuje kompletny system na 4, 8 lub 16 kamer i co wpływa na cenę.",
    tag: "Monitoring",
    date: "15 stycznia 2025",
    color: "#0D9F6E",
    icon: "📹",
    image: "/blog-cctv.jpg",
    content: [
      "Ceny systemów monitoringu CCTV w 2024 roku są najniższe w historii. Za kompletny zestaw 4 kamer IP z rejestratorem NVR zapłacisz już od 1800 zł netto — jeszcze 3 lata temu podobny system kosztował ponad 4000 zł.",
      "Na cenę systemu monitoringu wpływa przede wszystkim rozdzielczość kamer. Kamery 2MP (Full HD) to minimum na dzień dzisiejszy — obraz z kamer 720p jest zbyt mało szczegółowy, szczególnie przy identyfikacji osób. Kamery 4K (8MP) kosztują niewiele więcej, a różnica w jakości jest ogromna.",
      "Kolejny czynnik to typ kamer: kamery kopułowe (dla wnętrz) są tańsze od kamer tubowych (dla zewnętrza) z podobnymi parametrami. Kamery z diodami IR do nocnego widzenia kosztują ok. 200–400 zł brutto więcej niż kamery bez IR.",
      "Na rynku znajdziesz systemy zarówno polskich producentów (np. RVI, BCS), jak i globalnych marek (Hikvision, Dahua). Różnica w cenie między nimi zmniejszyła się — chińskie kamery Hikvision w segmencie konsumenckim są porównywalne cenowo z tańszymi odpowiednikami innych producentów.",
      "Pamiętaj też o kosztach okablowania (ok. 5–10 zł/mb kabla UTP), dysku twardego do nagrywania (od 200 zł za 1TB), oraz ewentualnie access pointów WiFi jeśli kamery są bezprzewodowe.",
    ],
  },
  {
    slug: "backup-danych-firmowych",
    title: "Dlaczego firmy tracą dane i jak temu zapobiec?",
    excerpt:
      "85% firm, które straciły dane i nie miały kopii zapasowych, zbankrutowało w ciągu 2 lat. Sprawdź, jak zabezpieczyć firmę przed utratą danych.",
    tag: "Backup",
    date: "8 stycznia 2025",
    color: "#3B82F6",
    icon: "💾",
    image: "/blog-siec.jpg",
    content: [
      "Według badań Small Business Trends, 85% firm bez działających kopii zapasowych bankrutuje w ciągu dwóch lat po poważnej utracie danych. Dla małych i średnich przedsiębiorstw utrata bazy klientów, dokumentacji księgowej czy korespondencji może być katastrofalna.",
      "Najczęstsze przyczyny utraty danych to: awarie dysków twardych (40%), błędy ludzkie (29%), ataki ransomware (13%), pożary i zalania (9%), i kradzieże (9%). Co ciekawe, większość przypadków wynika z prostych błędów — nie z wyrafinowanych ataków hakerskich.",
      "Reguła 3-2-1 to podstawa: miej co najmniej 3 kopie danych, na 2 różnych nośnikach (np. dysk lokalny + chmura), z czego 1 kopię poza siedzibą firmy. Dla większości firm oznacza to: codzienny backup do chmury (np. Backblaze B2, Wasabi) + tygodniowy na zewnętrzny dysk.",
      "Backupy lokalne (tylko na dysku w biurze) nie są wystarczające — ransomware potrafi zaszyfrować również dyski USB podłączone do komputera. Backup do chmury jest odporny na fizyczne zniszczenie sprzętu i szyfrowanie przez oprogramowanie szantażujące.",
      "Testuj regularnie! Statystycznie 77% firm odkrywa problemy z backupem dopiero przy próbie odtworzenia danych. Co miesiąc sprawdzaj, czy backupy działają i czy dane da się odtworzyć.",
    ],
  },
  {
    slug: "dlaczego-firma-potrzebuje-it-outsourcingu",
    title: "Dlaczego firmy decydują się na outsourcing IT?",
    excerpt:
      "Outsourcing działu IT pozwala firmom zaoszczędzić średnio 40% kosztów przy jednoczesnej poprawie jakości obsługi. Poznaj korzyści i wady.",
    tag: "IT dla firm",
    date: "2 stycznia 2025",
    color: "#8B5CF6",
    icon: "💼",
    image: "/blog-erp.jpg",
    content: [
      "Outsourcing IT to przekazanie obsługi informatycznej zewnętrznej firmie zamiast zatrudniania własnego specjalisty lub działu IT. Dla małych i średnich firm to często najbardziej ekonomiczne rozwiązanie — koszt abonamentu IT (od 600 zł/mc) jest znacznie niższy niż pensja even jednego informatyká (4500–8000 zł/mc brutto).",
      "Główne korzyści: brak kosztów zatrudnienia i szkoleń, dostęp do zespołu ekspertów (nie jednej osoby), przewidywalne koszty miesięczne, brak przestojów związanych z urlopami i chorobami, szybsza reakcja dzięki dyżurom.",
      "Wady do rozważenia: mniejsza integracja z firmą (zewnętrzny dostawca zna firmę mniej niż własny informatyk), konieczność jasnego definiowania zakresu usług, potencjalne opóźnienia w przypadku prostych zadań wymagających obecności fizycznej.",
      "Outsourcing sprawdza się szczególnie w firmach do 50 stanowisk, gdzie zatrudnienie całego działu IT byłoby nieuzasadnione ekonomicznie, a pojedynczy informatyk stanowi ryzyko (jego absencja = paraliż).",
      "Przy wyborze dostawcy zwróć uwagę na: czas reakcji (gwarantowany w umowie SLA), zakres usług w cenie abonamentu, możliwość eskalacji, doświadczenie w branży klienta, opinie innych firm.",
    ],
  },
];
